### ISSUE TITLE
Remove large dataset from package

### ISSUE THREAD

**Issue by trangdata** [insilico/glmSTIR#7]
I think we want to remove [mdd.RNAseq.rda](https://github.com/insilico/npdr/blob/master/data/mdd.RNAseq.rda) from the package and replace it with a smaller dataset (perhaps a smaller number of randomly selected genes or just top genes).

**Comment by brett-mckinney** [comment]
Might have been the data used in the npdr paper. I don't think we use it anywhere in the package.
